### ISSUE TITLE
@ubjs/node: published types do not declare `FfiType` or `resolveLibPath` (TS2339 in every napi `-ffi.ts`)

### ISSUE THREAD

**Issue by neekolas** [jhugman/uniffi-bindgen-react-native#476]
## Summary

Every generated napi `-ffi.ts` starts with:

```ts
const { UniffiNativeModule, FfiType, resolveLibPath } = lib;
```

`@ubjs/node` (`runtimes/napi/package.json`) has `"main": "lib.js"` and `"types": "index.d.ts"`. `lib.js` adds `FfiType`, `resolveLibPath` and `ResolveLibPathError` to the native exports at runtime. But `index.d.ts` is made by NAPI-RS from the Rust code only, and it does not declare these three names. So a project that uses the napi flavour with `strictTypeChecking = true` gets TS2339 in every generated `-ffi.ts`. The code runs correctly.

CI does not find this, because the fixture harness maps `@ubjs/node` to `runtimes/napi/lib.js` (a `.js` file) and runs the tests with `tsx`, which does not type-check.

## Steps to reproduce

On `main` at f5865e7.

```sh
git clone https://github.com/jhugman/uniffi-bindgen-react-native ubrn
cd ubrn && git checkout f5865e7
cargo xtask bootstrap yarn
(cd runtimes/napi && npm ci && npm run build:debug)

# The published types do not declare the names that lib.js adds:
grep -n '"main"\|"types"' runtimes/napi/package.json
grep -c 'FfiType\|resolveLibPath' runtimes/napi/index.d.ts      # 0
grep -n 'resolveLibPath\|FfiType:' runtimes/napi/lib.js

# Generate and type-check a napi fixture with real module resolution:
cargo test -p uniffi-fixture-callbacks -- napi::                # passes
cat > /tmp/napi-tsconfig.json <<EOF
{ "compilerOptions": { "strict": true, "noEmit": true, "target": "es2022",
    "module": "nodenext", "moduleResolution": "nodenext", "skipLibCheck": true,
    "allowImportingTsExtensions": true,
    "paths": { "@ubjs/core": ["$PWD/typescript/src/index.ts"],
               "@ubjs/node": ["$PWD/runtimes/napi/index.d.ts"] } },
  "files": ["$PWD/fixtures/callbacks/generated/napi/ts/callbacks-ffi.ts"] }
EOF
node_modules/.bin/tsc -p /tmp/napi-tsconfig.json
```

## Expected

`tsc` reports no errors: the `@ubjs/node` types declare every name that `lib.js` exports.

## Actual

```
generated/napi/ts/callbacks-ffi.ts(4,29): error TS2339: Property 'FfiType' does not exist on type 'typeof import(".../runtimes/napi/index")'.
generated/napi/ts/callbacks-ffi.ts(4,38): error TS2339: Property 'resolveLibPath' does not exist on type 'typeof import(".../runtimes/napi/index")'.
```

The uniffi 0.32 stack tip (8f26a10) is the same.

## Notes / suggested fix

- Add a hand-written `runtimes/napi/lib.d.ts` that re-exports `./index` and declares `FfiType`, `resolveLibPath` and `ResolveLibPathError`. Then set `"types": "lib.d.ts"` in `runtimes/napi/package.json`, and include the file in the published package.
- A type-check step for the napi fixture tests would find this in CI. See #477.

Found while working on the uniffi 0.32.1 upgrade (#449).

🤖 Generated with [Claude Code](https://claude.com/claude-code)
