### ISSUE TITLE
CI: napi, wasm and wasm2 fixture tests do not type-check the generated TypeScript

### ISSUE THREAD

**Issue by neekolas** [jhugman/uniffi-bindgen-react-native#477]
## Summary

The fixture harness type-checks the generated TypeScript only for the JSI flavour. For JSI, `typescript::prepare_for_jsi` compiles the test script and the generated bindings with `tsc` and `"strict": true` before it runs them on Hermes. For napi, wasm and wasm2, the harness runs the test script directly with `tsx`. `tsx` removes the types and does not check them.

So a type error in the generated code for these flavours (or in a test script) does not fail CI, if the code still runs. Some errors of this type are on `main` now (see "Actual").

This is an enhancement to CI, not a runtime bug.

## Steps to reproduce

On `main` at f5865e7. Set up the tools as in `.github/workflows/ci.yml` (`cargo xtask bootstrap yarn`, `cargo xtask bootstrap`, the `wasm32-unknown-unknown` target, `wasm-bindgen-cli` 0.2.114, and `cd runtimes/napi && npm ci && npm run build:debug`).

1. Plant a type error in a fixture test script:

```sh
cat >> fixtures/enum-types/tests/bindings/test_enum_types.ts <<'EOF'

// PLANTED TYPE ERROR: a string is assigned to a number.
const plantedTypeError: number = "not a number";
console.log("planted value:", plantedTypeError);
EOF

for fl in napi wasm2 wasm jsi; do cargo test -p uniffi-fixture-enum-types -- $fl::; done
git checkout fixtures/enum-types/tests/bindings/test_enum_types.ts
```

2. Type-check the generated code that the passing CI tests use. For example, after `cargo test -p uniffi-fixture-callbacks -- wasm::` and `-- napi::` (both pass), run `tsc` with `"strict": true` on `fixtures/callbacks/generated/wasm/ts/callbacks-ffi.ts` (`fixtures/callbacks/uniffi.toml` sets `strictTypeChecking = true`, so these files do not have `// @ts-nocheck`.)

## Expected

The napi, wasm and wasm2 tests fail on a type error, as the jsi test does.

## Actual

1. Only jsi fails. The other flavours run the file and print the value:

```
napi:  planted value: not a number
       test napi::test_enum_types ... ok
wasm2: planted value: not a number
       test wasm2::test_enum_types ... ok
wasm:  planted value: not a number
       test wasm::test_enum_types ... ok
jsi:   tests/bindings/test_enum_types.ts(293,7): error TS2322: Type 'string' is not assignable to type 'number'.
       test jsi::test_enum_types ... FAILED
```

2. Type errors in generated code that CI does not find today:

```
# wasm, callbacks fixture (test passes)
generated/wasm/ts/callbacks-ffi.ts(40,6): error TS2304: Cannot find name 'UniffiResult'.
generated/wasm/ts/callbacks-ffi.ts(43,6): error TS2304: Cannot find name 'UniffiResult'.
generated/wasm/ts/callbacks-ffi.ts(66,6): error TS2304: Cannot find name 'UniffiResult'.
```

Other examples that CI does not find today: #471 (tuple variant with an `Option` field, TS2345), #472 (`UniffiResult` not imported in the wasm `-ffi.ts`) and #476 (`@ubjs/node` types, TS2339 in every napi `-ffi.ts`).

The harness on the uniffi 0.32 stack tip (8f26a10) is the same.

## Notes / suggested fix

- `crates/ubrn_fixture_testing/src/napi.rs:80-83`, `wasm.rs:93-99` and `wasm2.rs:57-62` call `tsx` (`lib.rs:217-239`). JSI uses `typescript::prepare_for_jsi` (`typescript.rs`), which runs `tsc` with the strict template `typescript/tsconfig.template.json`.
- Add a `tsc --noEmit` step with `"strict": true` before `tsx` for napi, wasm and wasm2. The fixture `tsconfig.json` from `write_fixture_tsconfig` (`lib.rs:158-185`) can be used if it gets `"strict": true` and a typed mapping for `@ubjs/node`.
- The new check fails until #471, #472 and #476 are fixed. For napi, the check must resolve `@ubjs/node` to its published types, not to `lib.js`.

Found while working on the uniffi 0.32.1 upgrade (#449).

🤖 Generated with [Claude Code](https://claude.com/claude-code)
