### ISSUE TITLE
CI: compat tests skip the Android turbo-module build (disabled since #268)

### ISSUE THREAD

**Issue by neekolas** [jhugman/uniffi-bindgen-react-native#475]
## Summary

The compat workflow (`compat-pr.yml`, `compat-nightly.yml` → `compat.yml`) runs `.github/actions/test-turbo-modules` for iOS and for Android. For Android, the action only runs the comparison test. The step "Generate & build turbo module" is skipped:

```yaml
    - name: Generate & build turbo module
      # Disable the perma-failing android
      if: ${{ inputs.platform != 'android' }}
```

This condition came in with d8338c8 "Bugfix for ts bindings (#268)" on 2025-06-10. The PR has no description, and no issue tracks it. Since then, CI never builds a generated turbo module for Android. The Android compat jobs are green, but they do not compile or link any ubrn output for Android.

When I run the Android build locally on `main`, it still fails (see "Actual").

## Steps to reproduce

On `main` at f5865e7.

1. Confirm the skip from the file and the history:

```sh
grep -n -B1 -A2 'perma-failing' .github/actions/test-turbo-modules/action.yml
git log --format='%h %ad %s' --date=short -S'perma-failing' -- .github/actions/test-turbo-modules/action.yml
```

2. Confirm that the Android compat jobs do not run the build. In the nightly run 35800728306 (2026-09-23, on f5865e7), the log of an Android job has no line with `turbo-module-for-building`. The log of an iOS job has 67:

```sh
gh run view 35800728306 -R jhugman/uniffi-bindgen-react-native --json jobs \
  --jq '.jobs[] | select(.name|test("· rn")) | "\(.databaseId) \(.name)"'
gh run view -R jhugman/uniffi-bindgen-react-native --job <android job id> --log | grep -c turbo-module-for-building   # 0
gh run view -R jhugman/uniffi-bindgen-react-native --job <ios job id> --log | grep -c turbo-module-for-building       # 67
```

3. Optional: run the skipped step locally (macOS, Android SDK and NDK installed, JDK 17, `cargo-ndk`):

```sh
./scripts/test-turbo-modules.sh \
  --slug '@my-org/my-lib' \
  --ubrn-config integration/fixtures/compat/ubrn.config.yaml \
  --builder-bob-version latest --rn-version latest \
  --package-json-mixin integration/fixtures/compat/package.json \
  --react-native-config integration/fixtures/compat/react-native.config.js \
  --android \
  ../turbo-module-for-building
```

## Expected

CI builds the generated Android turbo module, as it does for iOS. If the Android build is known to fail, an open issue tracks it.

## Actual

1.

```
63-    - name: Generate & build turbo module
64:      # Disable the perma-failing android
65-      if: ${{ inputs.platform != 'android' }}
d8338c8 2025-06-10 Bugfix for ts bindings (#268)
```

The 0.32 stack tip (8f26a10) has the same lines.

3. The local Android build (React Native 0.87.1, create-react-native-library `latest`, run on 2026-09-22) fails in the example app. `ubrn build android --and-generate` succeeds; the Gradle build of the example app does not:

```
> Task :app:buildCMakeDebug[arm64-v8a] FAILED
.../example/android/app/build/generated/autolinking/src/main/jni/autolinking.cpp:10:10: fatal error: 'MyLibSpec.h' file not found
   10 | #include <MyLibSpec.h>
BUILD FAILED in 2m 9s
❌ Error: Failed to build Android example
```

A possible cause: `integration/fixtures/compat/react-native.config.js` sets `cmakeListsPath: "tmp/jni/CMakeLists.txt"`, and `integration/fixtures/compat/package.json` sets `codegenConfig.outputDir.android` to `android/tmp`. This is the setup that `docs/src/reference/config-yaml.md:103` tells users to use. But the library codegen wrote `MyLibSpec.h` to `android/build/generated/source/codegen/jni/`, and `android/tmp/` was not created. The generated `Android-autolinking.cmake` then skips the library:

```
React Native: Skipping autolinked library 'react_codegen_MyLibSpec' because the source directory does not exist: .../turbo-module-for-building/android/tmp/jni/
```

I did not confirm this cause further.

## Notes / suggested fix

- `.github/actions/test-turbo-modules/action.yml:63-65`: remove the `if:` after the Android build is fixed. Until then, an open issue that links to this condition makes the gap visible.
- Check if React Native still uses `codegenConfig.outputDir.android` for a library. If not, the compat fixture and the warning in `docs/src/reference/config-yaml.md:103` need an update, because users who follow the docs can get the same error.

Found while working on the uniffi 0.32.1 upgrade (#449).

🤖 Generated with [Claude Code](https://claude.com/claude-code)
