### ISSUE TITLE
Tuple enum variant with Option field fails strictTypeChecking (TS2345)

### ISSUE THREAD

**Issue by neekolas** [jhugman/uniffi-bindgen-react-native#471]
## Summary

For a tagged enum with a tuple (unnamed) variant that holds an `Option<T>`, the generated constructor and the `inner` tuple type use `T`, not `T | undefined`. The generated FfiConverter reads an `Option<T>` (type `T | undefined`) and passes it to that constructor. With `strictTypeChecking = true`, the generated file does not compile (TS2345). User code also cannot pass `undefined` to the variant constructor.

This happens on all four flavours (jsi, napi, wasm, wasm2). Named variants and records are not affected, because they use `name?: T`.

## Steps to reproduce

On `main` at f5865e7 (uniffi 0.31.2).

Build ubrn and install the TypeScript tools:

```sh
git clone https://github.com/jhugman/uniffi-bindgen-react-native ubrn
cd ubrn && git checkout f5865e7
cargo build -p uniffi-bindgen-react-native
cargo xtask bootstrap yarn
UBRN=$PWD
```

Make a probe crate outside the ubrn checkout.

`Cargo.toml`:

```toml
[package]
name = "opttuple"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
uniffi = "=0.31"

[workspace]
```

`src/lib.rs`:

```rust
#[derive(uniffi::Enum)]
pub enum E { N(Option<Vec<i32>>), L }

#[uniffi::export]
fn f(_e: E) {}

uniffi::setup_scaffolding!();
```

`uniffi.toml`:

```toml
[bindings.typescript]
strictTypeChecking = true
```

`tsconfig.json` (the shell expands `$UBRN`):

```sh
cat > tsconfig.json <<EOF
{ "compilerOptions": { "strict": true, "noEmit": true, "target": "es2022", "lib": ["es2024", "dom"],
    "module": "esnext", "moduleResolution": "bundler", "skipLibCheck": true,
    "allowImportingTsExtensions": true, "types": [],
    "paths": { "@ubjs/core": ["$UBRN/typescript/src/index.ts"] } },
  "files": ["out/jsi/ts/opttuple.ts"] }
EOF
```

Commands (macOS; use `.so` on Linux):

```sh
cargo build
$UBRN/target/debug/uniffi-bindgen-react-native generate bindings --library --flavor jsi \
  --ts-dir out/jsi/ts --cpp-dir out/jsi/cpp target/debug/libopttuple.dylib
$UBRN/node_modules/.bin/tsc -p tsconfig.json
```

## Expected

`tsc` reports no errors. The variant is declared as:

```ts
readonly inner: Readonly<[Array<number> | undefined]>;
constructor(v0: Array<number> | undefined) { ... }
```

## Actual

```
out/jsi/ts/opttuple.ts(114,40): error TS2345: Argument of type 'number[] | undefined' is not assignable to parameter of type 'number[]'.
  Type 'undefined' is not assignable to type 'number[]'.
```

The generated code (whitespace trimmed):

```ts
        readonly inner: Readonly<[Array<number>]>;
        constructor(v0: Array<number>) {
...
                case 1: return new E.N(FfiConverterOptionalSequenceInt32.readFromCursor(c));
```

The same TS2345 is reported for the napi, wasm and wasm2 output of this crate. It also happens on the uniffi 0.32 stack tip (8f26a10, uniffi 0.32.1).

## Notes / suggested fix

- `crates/ubrn_bindgen/src/bindings/gen_typescript/api_module/builders.rs:237-247` (`build_field`) unwraps `Optional<T>` to `T` in `ts_type`. It expects the template to add `?:`. That is correct for named fields (`field_decl`), but tuple fields have no name.
- `crates/ubrn_bindgen/src/bindings/gen_typescript/templates/CallBodyMacros.ts:380` (`variant_inner_type`) and `:392` (`variant_fields_decl`) emit `field.ts_type` for nameless fields. When `field.is_optional`, they must emit `{{ field.ts_type }} | undefined`.
- CI did not find this, because only the jsi harness type-checks the generated code, and no fixture has this shape. See the separate issue about type checks for the napi/wasm/wasm2 fixture tests.

Found while working on the uniffi 0.32.1 upgrade (#449).

🤖 Generated with [Claude Code](https://claude.com/claude-code)
