### ISSUE TITLE
wasm flavour: generated `-ffi.ts` uses `UniffiResult` without importing it (TS2304 with callback interfaces)

### ISSUE THREAD

**Issue by neekolas** [jhugman/uniffi-bindgen-react-native#472]
## Summary

(a) For the `wasm` flavour (wasm-bindgen, `--flavor wasm`), the generated `<namespace>-ffi.ts` has no imports. When the crate has a callback interface, the file declares the clone type as `(handle: bigint) => UniffiResult<void>`, but `UniffiResult` is not imported. With `strictTypeChecking = true`, `tsc` reports TS2304. The existing `callbacks` fixture has this error too (see below), but CI does not find it, because the wasm fixture tests run through `tsx`, which does not type-check.

(b) Smaller: the `-ffi.ts` made from `wrapper-ffi-player.ts` (napi and wasm2) imports `RuntimeUniffiRustFutureContinuationCallback`, but the template never uses it. The same is true for `UniffiStructuralEquality`, `RuntimeUniffiForeignFuture` and `UniffiGcObject`. This is not an error with `strict`. It only shows as TS6133 when a consumer compiles the generated code with `noUnusedLocals: true`.

## Steps to reproduce

On `main` at f5865e7 (uniffi 0.31.2).

```sh
git clone https://github.com/jhugman/uniffi-bindgen-react-native ubrn
cd ubrn && git checkout f5865e7
cargo build -p uniffi-bindgen-react-native
cargo xtask bootstrap yarn
UBRN=$PWD
```

Make a probe crate outside the ubrn checkout.

`Cargo.toml`:

```toml
[package]
name = "cbprobe"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
uniffi = "=0.31"

[workspace]
```

`src/lib.rs`:

```rust
#[uniffi::export(callback_interface)]
pub trait Listener: Send + Sync {
    fn on_value(&self, v: i32) -> i32;
}

#[uniffi::export]
fn call_listener(l: Box<dyn Listener>, v: i32) -> i32 { l.on_value(v) }

uniffi::setup_scaffolding!();
```

`uniffi.toml`:

```toml
[bindings.typescript]
strictTypeChecking = true
```

Commands (macOS; use `.so` on Linux):

```sh
cargo build

# (a)
$UBRN/target/debug/uniffi-bindgen-react-native generate bindings --library --flavor wasm \
  --ts-dir out/wasm/ts --cpp-dir out/wasm/rs target/debug/libcbprobe.dylib
$UBRN/node_modules/.bin/tsc --strict --noEmit --target es2022 out/wasm/ts/cbprobe-ffi.ts

# (b)
$UBRN/target/debug/uniffi-bindgen-react-native generate bindings --library --flavor wasm2 \
  --ts-dir out/wasm2/ts --cpp-dir out/wasm2/rs target/debug/libcbprobe.dylib
grep -n 'RuntimeUniffiRustFutureContinuationCallback' out/wasm2/ts/cbprobe-ffi.ts
```

The existing fixture shows (a) too. Inside the ubrn checkout:

```sh
cargo test -p uniffi-fixture-callbacks -- wasm::      # passes
grep -n 'UniffiResult\|^import' fixtures/callbacks/generated/wasm/ts/callbacks-ffi.ts
```

## Expected

(a) `tsc` reports no errors: the file imports `type UniffiResult` from `@ubjs/core`, as the jsi `-ffi.ts` does.

(b) The player `-ffi.ts` imports only the types it uses.

## Actual

(a)

```
out/wasm/ts/cbprobe-ffi.ts(15,72): error TS2304: Cannot find name 'UniffiResult'.
```

The generated `callbacks-ffi.ts` of the `callbacks` fixture gives the same error three times (lines 40, 43 and 66), and `cargo test -p uniffi-fixture-callbacks -- wasm::` passes.

(b) The import is present, but nothing in the file uses it:

```
13:  type UniffiRustFutureContinuationCallback as RuntimeUniffiRustFutureContinuationCallback,
```

With `noUnusedLocals: true`:

```
cbprobe-ffi.ts(9,30): error TS6133: 'UniffiStructuralEquality' is declared but its value is never read.
cbprobe-ffi.ts(10,31): error TS6133: 'RuntimeUniffiForeignFuture' is declared but its value is never read.
cbprobe-ffi.ts(12,8): error TS6133: 'UniffiGcObject' is declared but its value is never read.
cbprobe-ffi.ts(13,48): error TS6133: 'RuntimeUniffiRustFutureContinuationCallback' is declared but its value is never read.
```

(The generated `cbprobe.ts` also has unused imports, so `noUnusedLocals` is not clean for any flavour. This part is only a tidy-up.)

Both (a) and (b) also happen on the uniffi 0.32 stack tip (8f26a10, uniffi 0.32.1).

## Notes / suggested fix

- (a) `crates/ubrn_bindgen/src/bindings/gen_typescript/templates/wrapper-ffi.ts:9-18`: the `@ubjs/core` import is inside `{%- if module.is_jsi %}`. The callback type aliases after it use `UniffiResult` for every flavour (it comes from `ffi_module/builder.rs:284`). Move `import { type UniffiResult } from '@ubjs/core';` out of the `is_jsi` block, or emit it when the module has callback interfaces.
- (b) `crates/ubrn_bindgen/src/bindings/gen_typescript/templates/wrapper-ffi-player.ts:20-27`: remove the unused type imports, or guard them like `wrapper-ffi.ts` does with `{%- if module.has_continuation_callback %}`.

Found while working on the uniffi 0.32.1 upgrade (#449).

🤖 Generated with [Claude Code](https://claude.com/claude-code)
