### ISSUE TITLE
Custom type over a record in a type cycle: FfiConverter used before it is declared (ReferenceError at load)

### ISSUE THREAD

**Issue by neekolas** [jhugman/uniffi-bindgen-react-native#473]
## Summary

A custom type whose builtin type is a record (or an enum) is emitted as an alias:

```ts
const FfiConverterTypeWrapped = FfiConverterTypeInner;
```

This line is evaluated when the module loads. When the record is in a type cycle, the generated file can put this alias **before** `const FfiConverterTypeInner = ...`. The module then throws `ReferenceError: Cannot access 'FfiConverterTypeInner' before initialization` when it is imported, on every flavour. With `strictTypeChecking = true`, `tsc` also reports TS2448.

Without the cycle, the order is correct (`FfiConverterTypeInner` first, then the alias).

## Steps to reproduce

On `main` at f5865e7 (uniffi 0.31.2). uniffi 0.31 has no `Box<T>` support, so the cycle goes through `Vec<T>`.

Build ubrn, the TypeScript tools, and the napi runtime:

```sh
git clone https://github.com/jhugman/uniffi-bindgen-react-native ubrn
cd ubrn && git checkout f5865e7
cargo build -p uniffi-bindgen-react-native
cargo xtask bootstrap yarn
(cd runtimes/napi && npm ci && npm run build:debug)
UBRN=$PWD
```

Make a probe crate outside the ubrn checkout.

`Cargo.toml`:

```toml
[package]
name = "customcycle"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
uniffi = "=0.31"

[workspace]
```

`src/lib.rs`:

```rust
// A custom type over a record, and the record is in a cycle
// (Inner -> Vec<ViaCustom> -> Wrapped -> Inner).
#[derive(uniffi::Record)]
pub struct Inner { pub e: Vec<ViaCustom> }

pub struct Wrapped(pub Inner);
uniffi::custom_newtype!(Wrapped, Inner);

#[derive(uniffi::Enum)]
pub enum ViaCustom { W { w: Wrapped }, L }

#[uniffi::export]
fn id(v: ViaCustom) -> ViaCustom { v }

uniffi::setup_scaffolding!();
```

`uniffi.toml`:

```toml
[bindings.typescript]
strictTypeChecking = true
```

Commands (macOS; use `.so` on Linux):

```sh
cargo build

# 1. Load the napi bindings in Node.
$UBRN/target/debug/uniffi-bindgen-react-native generate napi bindings --lib-colocated --library \
  --ts-dir gen target/debug/libcustomcycle.dylib
cat > tsconfig.json <<EOF
{ "compilerOptions": { "baseUrl": ".", "paths": {
    "@ubjs/core": ["$UBRN/typescript/src/index.ts"],
    "@ubjs/node": ["$UBRN/runtimes/napi/lib.js"] } } }
EOF
echo 'import * as m from "./gen/customcycle.ts"; console.log("loaded", Object.keys(m));' > load.ts
$UBRN/node_modules/.bin/tsx load.ts

# 2. Type-check the jsi bindings.
$UBRN/target/debug/uniffi-bindgen-react-native generate bindings --library --flavor jsi \
  --ts-dir gen-jsi/ts --cpp-dir gen-jsi/cpp target/debug/libcustomcycle.dylib
cat > tsconfig.jsi.json <<EOF
{ "compilerOptions": { "strict": true, "noEmit": true, "target": "es2022", "lib": ["es2024", "dom"],
    "module": "esnext", "moduleResolution": "bundler", "skipLibCheck": true,
    "allowImportingTsExtensions": true, "types": [],
    "paths": { "@ubjs/core": ["$UBRN/typescript/src/index.ts"] } },
  "files": ["gen-jsi/ts/customcycle.ts"] }
EOF
$UBRN/node_modules/.bin/tsc -p tsconfig.jsi.json
```

## Expected

`load.ts` prints `loaded [...]`. `tsc` reports no errors. `FfiConverterTypeInner` is declared before `FfiConverterTypeWrapped`.

## Actual

Node, at import time:

```
gen/customcycle.ts:41
const FfiConverterTypeWrapped = FfiConverterTypeInner;
                                ^

ReferenceError: Cannot access 'FfiConverterTypeInner' before initialization
```

tsc (jsi output):

```
gen-jsi/ts/customcycle.ts(41,33): error TS2448: Block-scoped variable 'FfiConverterTypeInner' used before its declaration.
gen-jsi/ts/customcycle.ts(41,33): error TS2454: Variable 'FfiConverterTypeInner' is used before being assigned.
```

Order of the converters in the generated file (the same on jsi, napi, wasm and wasm2):

```
41:  const FfiConverterTypeWrapped = FfiConverterTypeInner;
122: const FfiConverterTypeViaCustom = (() => {
187: const FfiConverterTypeInner = (() => {
```

It also happens on the uniffi 0.32 stack tip (8f26a10, uniffi 0.32.1), with the same ReferenceError in Node and TS2448 in tsc. On 0.32 the cycle can also go through `Option<Box<T>>`.

## Notes / suggested fix

- `crates/ubrn_bindgen/src/bindings/gen_typescript/api_module/mod.rs:395-405`: a custom type is deferred to after the base types only when its builtin is a `Map`, `Sequence` or `Optional`. For any other builtin, it is emitted at its place in uniffi's sorted `type_definitions`. Inside a cycle, that sort cannot put every type after its dependencies, so the custom type can come before its record.
- `templates/CustomTypeTemplate.ts:11` emits the eager alias `const {{ ffi_converter_name }} = {{ builtin_ffi_converter }};`.
- Possible fixes: also defer custom types whose builtin is a `Record`, `Enum` (or another `Custom`) to after all type definitions; or emit the alias lazily (for example, a small object that forwards to the builtin converter on first use).

Found while working on the uniffi 0.32.1 upgrade (#449).

🤖 Generated with [Claude Code](https://claude.com/claude-code)
